const reference = [
  {
    author: "",
    title: "해양생태계",
    year: "",
    sourceTitle: "해양환경정보포털",
    link: "https://www.meis.go.kr/mes/marineEcology/view1.do",
  },
  {
    author: "KIOST",
    title: "바다 생물들의 삶의 터전, 표영생태계",
    year: "2018",
    sourceTitle: "한국해양과학기술원공식블로그",
    link: "https://blog.naver.com/kordipr/221190496693",
  },
  {
    author: "",
    title: "해양생태계",
    year: "",
    sourceTitle: "국토환경정보센터",
    link: "https://www.neins.go.kr/mid=11050600",
  },
  {
    author: "",
    title: "Energy and Food Webs",
    year: "",
    sourceTitle: "OceanTracks",
    link: "https://oceantracks.org/library/general-ecology/energy-and-food-webs",
  },
  {
    author: "남성현",
    title: "벌거벗은 세계사 90화",
    year: "2023",
    sourceTitle: "",
    link: "",
  },
  {
    author: "",
    title: "산호초를 따라서",
    year: "2017",
    sourceTitle: "넷플릭스 다큐멘터리",
    link: "",
  },
  {
    author: "",
    title: "베어그릴스의 혹독한 야생 - 시즌1 2화 <바다>",
    year: "2019",
    sourceTitle: "내셔널지오그래픽",
    link: "",
  },
  {
    author: "",
    title: "산호가 열받았다",
    year: "2020",
    sourceTitle: "지식채널e",
    link: "",
  },
  {
    author: "최진기",
    title: "수요일엔 바다톡톡 해양강좌 - 산호초와 생태계",
    year: "2022",
    sourceTitle: "한국해양재단",
    link: "https://www.youtube.com/watch?v=3z_4DQS_pQ4",
  },
  {
    author: "",
    title: "산호가 동물이었다? 산호초에 대한 (거의)모든것",
    year: "2020",
    sourceTitle: "그린피스",
    link: "https://www.greenpeace.org/korea/update/15100/blog-ocean-taiwan-coral-bleaching/",
  },
  {
    author: "이강봉",
    title: "'해양의날'에 고통받는 산호초",
    year: "2023",
    sourceTitle: "사이언스타임즈",
    link: "https://www.sciencetimes.co.kr/news/%ED%95%B4%EC%96%91%EC%9D%98-%EB%82%A0%EC%97%90-%EA%B3%A0%ED%86%B5%EB%B0%9B%EB%8A%94-%EC%82%B0%ED%98%B8%EC%B4%88/",
  },
  {
    author: "조유미",
    title: "주변 바다 산소함량 높아 ... 해양생물 4분의 1살아요",
    year: "2022",
    sourceTitle: "조선멤버스",
    link: "http://newsteacher.chosun.com/site/data/html_dir/2022/12/20/2022122000056.html",
  },
  {
    author: "",
    title: "기후변화:엘니뇨와 라니냐는 전 세계에 어떤 영향을 미치나?",
    year: "2023",
    sourceTitle: "BBC뉴스 코리아",
    link: "https://www.bbc.com/korean/features-64245268",
  },
  {
    author: "",
    title: "Staghorn Coral",
    year: "",
    sourceTitle: "미국수산청 NOAA FISHERISH",
    link: "https://www.fisheries.noaa.gov/species/staghorn-coral",
  },
  {
    author: "",
    title: "내 나무갖기 캠페인",
    year: "2023",
    sourceTitle: "산림청",
    link: "https://www.forest.go.kr/kfsweb/kfi/kfs/cms/cmsView.do?mn=NKFS_02_01_02_08&cmsId=FC_003647",
  },
  {
    author: "",
    title: "세컨포레스트 회복의숲 캠페인",
    year: "2023",
    sourceTitle: "두나무x산림청",
    link: "http://www.2ndforest.kr",
  },
  {
    author: "",
    title: "nintendogs",
    year: "2005",
    sourceTitle: "nintendo",
    link: "https://www.nintendo.co.jp/ds/adgj/index.html",
  },
  {
    author: "원수연",
    title:
      "모바일과 PC에서 모두 즐길 수 있는 나만의 반려동물 키우기, 게임엔 미니펫",
    year: "2021",
    sourceTitle: "앱스토리",
    link: "https://news.appstory.co.kr/guide14729",
  },
  {
    author: "",
    title: "동물자유연대",
    year: "",
    sourceTitle: "",
    link: "https://www.animals.or.kr",
  },
  {
    author: "",
    title: "동물권행동 카라",
    year: "",
    sourceTitle: "",
    link: "https://ekara.org",
  },
  {
    author: "Amy Fraser",
    title: "그레이트 배리어 리프의 그레이트 에이트 만나기",
    year: "",
    sourceTitle: "호주정부관광청",
    link: "https://www.australia.com/ko-kr/things-to-do/wildlife/meet-the-great-barrier-reef-marine-animals.html",
  },
  {
    author: "Sofia Charalambous",
    title: "The corals of the Great Barrier Reef:illustrated",
    year: "2017",
    sourceTitle: "Australian Geographic",
    link: "https://www.australiangeographic.com.au/topics/science-environment/2017/06/the-corals-of-the-great-barrier-reef/",
  },
  {
    author: "",
    title: "",
    year: "",
    sourceTitle: "",
    link: "",
  },
  {
    author: "",
    title: "",
    year: "",
    sourceTitle: "",
    link: "",
  },
  {
    author: "",
    title: "",
    year: "",
    sourceTitle: "",
    link: "",
  },
];
